# Numerical Python

In [1]:
# ALWAYS RUN THIS CELL FIRST

from nose.tools import assert_equal  # tool for testing solutions
import numpy as np

### 1. Vector manipulation

Return a vector of zeros of size 10 but with the fifth value as 1. Function takes no inputs.

In [2]:
def vector_manipulation():
    """Returns a vector of zeros of size 10 but with the fifth value as 1.
    """
    # YOUR CODE HERE
    z=np.zeros(10)
    z[4]=1
    return z
    

In [3]:
"""(0.5 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

vectorm = vector_manipulation()

assert isinstance(vectorm, np.ndarray)
assert vectorm[:4].all() == 0
assert vectorm[4] == 1
assert vectorm[5:].all() == 0

print("Success!")

Success!


### 2. Vector range

Return a vector with values ranging from 10 to 49, inclusive. Do not write out each element in the array.

In [4]:
def vector_range():
    """Returns a vector with values ranging from 10 to 49, inclusive.
    """
    # YOUR CODE HERE
    return np.arange(10,50)

In [5]:
"""(0.5 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

vectorr = vector_range()
assert np.array_equal(vectorr, np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]))
assert isinstance(vectorr, np.ndarray)

print("Success!")

Success!


### 3. Reverse a vector

Write a function, `reverse(x)` which reverses a vector, so that the first element becomes the last element.

In [6]:
def reverse(vec):
    """return a 1D vector with the elements reversed

    Input
    -----
        x: 1D array

    Output
    ------
        res: 1D array, with the elements of `x` reversed
    """
    # YOUR CODE HERE
    return vec[::-1]




In [7]:
# if the array is n dimension
vec = np.arange(12).reshape(2,6)
print(vec)
print(vec.flat[::-1].reshape(2,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


In [8]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

vec = np.array([1, 2, 3, 4])
vector_reversed = reverse(vec)
assert np.array_equal(vector_reversed, np.array([4, 3, 2, 1]))
vec = np.array([-1, 9, 2.38])
vector_reversed = reverse(vec)
assert np.array_equal(vector_reversed, np.array([2.38, 9, -1]))
assert isinstance(vector_reversed, np.ndarray)

print("Success!")

Success!


### 4. Find indices of non-zero elements

A. Write a function `arg_nonzero(x)` that returns the indices of the non-zero elements of the input vector `x`.

B.  Write a function `use_find_nonzero(x, ind)` with an input vector `x` and indices of non-zero values, `ind`, found in part A, that returns the non-zero elements from array `x`.

In [9]:
# part A
def arg_nonzero(x):
    """return the indices of non-zero elements of an array.

    Inputs:
        x:  array
    
    Returns:
        indices: array of integer indices
    """
    # YOUR CODE HERE
    return np.where(x != 0)[0]

In [10]:
# part A
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

vec1 = np.array([1, 2, 0, 0, 4, 0])
assert np.array_equal(arg_nonzero(vec1), np.array([0, 1, 4]))
vec2 = np.array([-5, 0, 8, -2, 4, 10])
assert np.array_equal(arg_nonzero(vec2), np.array([0, 2, 3, 4, 5]))
vec3 = np.array([0, 0, 0, 0, 0, 0, 0, 3, 0])
assert np.array_equal(arg_nonzero(vec3), np.array([7]))

print("Success!")

Success!


In [11]:
# part B
def return_nonzero(x, ind):
    """return the indices of non-zero elements of an array.

    Inputs:
        x:  array
        output: results from call to find_nonzero(x)
    
    Returns:
        indices of non-zero element in x
    """
    # YOUR CODE HERE
#     for id in ind():
#         x2 = np.array([x[id]])

    return np.array([x[id] for id in ind])

In [12]:
# part B
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

ind1 = arg_nonzero(vec1)
assert np.array_equal(return_nonzero(vec1, ind1), np.array([1, 2, 4]))
ind2 = arg_nonzero(vec2)
assert np.array_equal(return_nonzero(vec2, ind2), np.array([-5, 8, -2, 4, 10]))
ind3 = arg_nonzero(vec3)
assert np.array_equal(return_nonzero(vec3, ind3), np.array([3]))

print("Success!")

Success!


### 5. Array with random values

Return a 10x30x3 array with normally distributed ($\mu=0,~\sigma=1)$ random values.

In [85]:
def random_array():
    """Return a 10x30x3 array with normally distributed ($\mu =0, \sigma=1)$ random values.
    """
    # YOUR CODE HERE
    a=np.random.normal(0,1,(10,30,3))
    return a

In [84]:
A = np.random.normal(0,1,(10,30,3))
A.shape


(10, 30, 3)

In [86]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

A = random_array()
assert A.shape == (10, 30, 3)  # check for shape
assert np.allclose(A.mean(), 0, atol=0.1)
assert np.allclose(A.std(), 1, atol=0.1)

print("Success!")

Success!


### 6. Operations on an array with random values

Fill in the code for a function, `maxesmins()`, which takes in an array and then returns 
- the minimum value of the 2nd row
- the maximum value of the 4th column
If there aren't enough rows or columns in the array to return either, return `np.nan` instead.

In [ ]:
def maxesmins(K):
    """Returns the min of the 2nd row and max of the 4th column.

    Parameters
    ----------
    K : numpy array
        
    Returns
    -------
    min of the 2nd row and max of the 4th column, as a tuple, or a nan for either if the array is too small to calculate it
    """
    # YOUR CODE HERE
    z=[np.nan,np.nan]
    if K[:,0].size>=2:
        z[0]=K[1,:].min()
    if K[0,:].size>=4: 
        z[1]=K[:,3].max()
    return tuple(z)
# if it's a  three dimension? 

In [ ]:
"""(2 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

L = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
assert (2, 8) == maxesmins(L)

M = np.ones((5, 5))
assert (1, 1) == maxesmins(M)

N = np.zeros((2, 2))
assert (0, np.nan) == maxesmins(N)

print("Success!")

### 7. Vector without end points

Return a vector of size 10 with values ranging from 0 to 1, both excluded. Do not explicitly write out the values in an array, but instead use a function to find them for you.

In [ ]:
def vector_end():
    """a vector of size 10 with values ranging from 0 to 1, both excluded
    """
    # YOUR CODE HERE
    return np.linspace( 0.09090909,0.90909091,10)


In [ ]:
np.linspace( 0.09090909,0.90909091,10)

In [ ]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

output_vector_end = np.array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])
assert (vector_end() == vector_end()).all()

print("Success!")

### 8. Sorted random vector

In `sorted_array()`, create, sort, and return a vector of size 10 filled with random numbers. It should be sorted in increasing order.

In [ ]:
def sorted_array():
    """Creates, sorts, and returns a vector of size 10 filled with random numbers
    """
    # YOUR CODE HERE
    a=np.random.rand(10)
    return np.sort(a)

In [ ]:
"""(1 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

sorted_array_output = sorted_array()

# check for proper size
assert sorted_array_output.size == 10
# check that array is sorted
assert (np.diff(sorted_array_output) > 0).all()

print("Success!")

### 9. Subtract the row mean from rows of a matrix

Fill in the code for the function `array_minus_row_mean` which takes in matrix, then subtracts the mean of each row of the matrix from the respective row. Do this without using a loop (that is, using array operations).

In [ ]:
def array_minus_row_mean(F):
    """Returns input array with the mean of each row subtracted from the respective row.
    
    Does not use a loop but instead uses array operations.
    
    Parameters
    ----------
    F : numpy array
        
    Returns
    -------
    F with mean of each row subtracted from the respective row
    """
    # YOUR CODE HERE
    F2=F.T.mean(axis=0)
    F3=F-F2[:,np.newaxis]
    return F3

In [ ]:
G = np.array([[1., 2.], [3., 4.]])
G2=G.T.mean(axis=0)
G-G2[:,np.newaxis]

In [ ]:
"""(2 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

G = np.ones((2, 3))
assert np.array_equal(array_minus_row_mean(G), np.zeros((2, 3)))

H = np.array([[1., 2.], [3., 4.]])
Hminus = np.array([[-0.5, 0.5], [-0.5, 0.5]])
assert np.array_equal(array_minus_row_mean(H), Hminus)

print("Success!")

### 10. Multiply arrays

Fill in the code in function `multiply_arrays` which takes in two arrays, $O$ and $P$, of shape (5,5,3) and (5,5), respectively, and returns $O$ times $P$, and $P$ times the transpose of $O$, respectively. Use the operator `*` for multiplication.

In [ ]:
def multiply_arrays(O, P):
    """Returns O times P and P times O transpose.
    
    Parameters
    ----------
    O: numpy array
        shape 5 x 5 x 3
    P: numpy array
        Shape 5 x 5
    
    Returns
    -------
    (O * P), (P * transpose(O)) 
    """
    # YOUR CODE HERE
    return [O*P[:,:,np.newaxis],P*O.transpose()]


In [ ]:
O = np.random.rand(5, 5, 3)
P = np.random.rand(5, 5)
P2=O*P[:,:,np.newaxis]
P3=P*O.transpose()
P2.shape
P3.shape

In [ ]:
"""(2 point) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

Q = np.random.rand(5, 5, 3)
R = np.random.rand(5, 5)
S, T = multiply_arrays(Q, R)

assert S.shape == (5, 5, 3)
assert T.shape == (3, 5, 5)

print("Success!")

### 11. Convert from Cartesian to polar coordinates

Write a function `cart2polar(xy)` which takes in an Nx2 matrix of `x, y` pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix.

In [74]:
def cart2polar(xy):
    """Convert input from Cartesian to polar coordinates.
    
    Parameters
    ----------
    xy : array
        Nx2 array of Cartesian coordinates, with columns of x and y coordinates, respectively.
        
    Returns
    -------
    rphi : array
        Coordinates Nx2 array containing input coordinates in polar representation, 
        with columns radius and angle, respectively.
    """
    # YOUR CODE HERE
    import math
 
    y1=xy[:,1]
    x1=xy[:,0]

    xy=x1**2+y1**2

    r=[]
    ar=[]
    for i in range(np.size(y1)):
        r.append(math.sqrt(xy[i]))
        ar.append(math.atan2(y1[i], x1[i]))

    rr=np.transpose([r,ar])
    return rr


In [44]:
import math
cart = np.random.rand(10, 2)
y1=cart[:,1]
x1=cart[:,0]

xy=x1**2+y1**2
xy.shape
r=[]
ar=[]
for i in range(np.size(y1)):
    r.append(math.sqrt(xy[i]))
    ar.append(math.atan2(y1[i], x1[i]))

rr=np.transpose([r,ar])
np.shape(rr)

(10, 2)

In [76]:
"""(3 points) Test code for the previous function. This cell should NOT give any errors when it is run.
Do not alter the contents of this cell."""

cart = np.random.rand(10, 2)
polar = cart2polar(cart)

assert polar.shape == (10, 2)  # check for shape

test_input = np.array([[1, 0]])
test_output = np.array([[1, 0]])
assert (cart2polar(test_input) == test_output).all()  #  check for known case [1, 0]

test_input = np.array([[0, 1]])
test_output = np.array([[1, np.pi/2]])
assert (cart2polar(test_input) == test_output).all()  #  check for known case [0, 1]

print("Success!")

Success!
